# Generated by Django 5.2.2 on 2025-10-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peeldb", "0061_alter_user_resume"),
    ]

    operations = []
