# Generated by Django 5.2.2 on 2025-10-27 21:44

import peeldb.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "peeldb",
            "0063_question_difficulty_mcqoption_skillassessmentattempt_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", peeldb.models.PeelUserManager()),
            ],
        ),
    ]
